-- Permit Templates Seed Data: 8 industries × 12 states

-- ============================================================
-- RESTAURANT / FOOD SERVICE
-- ============================================================

-- California
INSERT INTO public.permit_templates (industry, state_code, permit_name, category, typical_renewal_cycle, typical_cost_min, typical_cost_max, penalty_range_min, penalty_range_max, agency_name, agency_url, filing_type, required_docs, tips, is_one_time, sort_order) VALUES
('restaurant', 'CA', 'City Business License', 'Business', 'annual', 50, 500, 250, 1000, 'City Clerk / Finance Department', 'https://www.lacity.gov/government/popular-information/business-license', 'online', ARRAY['Business formation docs', 'Federal EIN', 'Owner ID'], 'Varies by city — Los Angeles fees are based on gross receipts. Renew by Dec 31 each year.', false, 1),
('restaurant', 'CA', 'Seller''s Permit', 'Tax', 'annual', 0, 0, 500, 5000, 'California Department of Tax and Fee Administration', 'https://www.cdtfa.ca.gov/formspubs/pub107.pdf', 'online', ARRAY['Federal EIN', 'SSN or ITIN', 'Business address'], 'Free to obtain. Must file sales tax returns (monthly/quarterly). No expiry but must update if business info changes.', false, 2),
('restaurant', 'CA', 'Health Department Permit (Retail Food Facility)', 'Health & Safety', 'annual', 400, 1000, 1000, 10000, 'County Environmental Health Department', 'https://www.cdph.ca.gov/Programs/CEH/DRSEM/CDPH%20Document%20Library/RetailFood/CDPH_278_ret_food_fac_permit.pdf', 'in_person', ARRAY['Floor plan', 'Equipment list', 'Food safety manager certificate', 'Menu'], 'Inspection required before permit issued. Fees vary by seating capacity. Los Angeles County: $400-$1,200/yr.', false, 3),
('restaurant', 'CA', 'ABC Liquor License (Type 41 - Beer/Wine)', 'Alcohol', 'annual', 300, 600, 2000, 20000, 'California Department of Alcoholic Beverage Control', 'https://www.abc.ca.gov/licensing/', 'in_person', ARRAY['Application form', 'Premises diagram', 'Background check', 'Public Notice', 'License fee'], 'Type 41 (beer/wine) is $300-$600/yr. Type 47 (full liquor) is $800-$1,200. Complex process — allow 3-6 months.', false, 4),
('restaurant', 'CA', 'Food Handler Card', 'Employee Certification', 'biennial', 15, 25, 100, 500, 'County Environmental Health', 'https://www.cal食品安全.gov/', 'online', ARRAY['Complete 8-hour food safety course', 'Pass exam', 'Photo ID'], 'All food handlers must have card within 30 days of hire. Cards valid 3 years. Online courses available for $15-25.', false, 5),
('restaurant', 'CA', 'Food Safety Manager Certification (ServSafe)', 'Employee Certification', 'biennial', 100, 175, 500, 2000, 'ANSI-accredited provider (e.g., ServSafe)', 'https://www.servsafe.com/', 'online', ARRAY['Complete 8-hour course', 'Pass proctored exam', 'Valid ID'], 'At least one certified Food Safety Manager required per establishment. Valid 5 years. Exam $36 + class fee.', false, 6),
('restaurant', 'CA', 'Fire Department Permit', 'Health & Safety', 'annual', 200, 600, 500, 5000, 'City/County Fire Department', 'https://www.lafd.org/fire-prevention/permits', 'in_person', ARRAY['Inspection request', 'Business license copy', 'Floor plan with exit routes'], 'Annual inspection required. Covers suppression systems, exit signs, fire extinguishers. Must post permit visibly.', false, 7),
('restaurant', 'CA', 'Building/Occupancy Permit (Certificate of Occupancy)', 'Building', 'one_time', 500, 5000, 5000, 50000, 'City/County Building Department', null, 'in_person', ARRAY['Architect plans', 'Building permit application', 'Site plan', 'ADA compliance certification'], 'Required before opening. Triggered by new construction or major remodel. Keep permanently on file.', true, 8),
('restaurant', 'CA', 'Signage Permit', 'Building', 'one_time', 50, 500, 100, 1000, 'City Planning / Building Department', null, 'in_person', ARRAY['Sign dimensions and design', 'Mounting location plan', 'Business license'], 'Required for any exterior sign. Illuminated signs need electrical permit too.', true, 9),
('restaurant', 'CA', 'Workers'' Compensation Insurance', 'Insurance', 'annual', 2000, 15000, 10000, 100000, 'California Department of Industrial Relations', 'https://www.dir.ca.gov/dwc/wcinsurance.htm', 'online', ARRAY['Payroll records', 'Business classification', 'Prior claims history'], 'Mandatory for any business with 1+ employees. Failure = $1,500/day fine. Rates vary by industry classification.', false, 10),
('restaurant', 'CA', 'Employer Identification Number (EIN)', 'Business', 'one_time', 0, 0, 10000, 50000, 'IRS', 'https://www.irs.gov/businesses/small-businesses-self-employed/apply-for-an-employer-identification-number-ein-online', 'online', ARRAY['SSN or ITIN', 'Business structure docs'], 'Free, instant online. Required to hire employees. Keep permanently — does not expire.', true, 11),
('restaurant', 'CA', 'Music/Entertainment License (ASCAP/BMI)', 'Entertainment', 'annual', 200, 1000, 500, 30000, 'ASCAP / BMI / SESAC', 'https://www.ascap.com/music-users/type/restaurant', 'online', ARRAY['Seating capacity', 'Music description (live/recorded)', 'Hours of operation'], 'Required if playing copyrighted music — covers streaming, radio, and live performance. ASCAP + BMI together = ~$500-1,500/yr.', false, 12),
('restaurant', 'CA', 'ADA Compliance (Physical Access)', 'Accessibility', 'one_time', 1000, 50000, 10000, 150000, 'U.S. DOJ / California DPOR', 'https://www.ada.gov/resources/small-business/', 'in_person', ARRAY['Accessibility audit', 'Remediation plan', 'Architect certification'], 'Not a permit but a legal requirement. Ramps, accessible restrooms, parking. CASp inspection recommended ($300-600).', true, 13);

-- Texas
INSERT INTO public.permit_templates (industry, state_code, permit_name, category, typical_renewal_cycle, typical_cost_min, typical_cost_max, penalty_range_min, penalty_range_max, agency_name, agency_url, filing_type, required_docs, tips, is_one_time, sort_order) VALUES
('restaurant', 'TX', 'City Business License/Permit', 'Business', 'annual', 25, 200, 200, 1000, 'City Secretary / Finance Office', null, 'online', ARRAY['Business formation docs', 'Federal EIN', 'Owner ID'], 'Texas has no state business license — cities issue their own. Dallas: $25-75/yr. Houston has no general business license.', false, 1),
('restaurant', 'TX', 'Retail Food Establishment Permit', 'Health & Safety', 'annual', 100, 700, 500, 5000, 'Texas Department of State Health Services', 'https://www.dshs.texas.gov/environmental/retail-food', 'online', ARRAY['Application', 'Floor plan', 'Food safety manager cert', 'Equipment list'], 'Class I (low risk): $100-200. Class IV (high risk, full service): $400-700. Inspection required.', false, 2),
('restaurant', 'TX', 'TABC License (Beer/Wine/Liquor)', 'Alcohol', 'annual', 500, 2500, 2000, 25000, 'Texas Alcoholic Beverage Commission', 'https://www.tabc.texas.gov/', 'online', ARRAY['Application', 'Criminal background check', 'Floor plan', 'Diagrams', 'Surety bond'], 'Mixed beverage permit: $3,000-6,000. Beer/wine only: $500-800. Allow 60-90 days. Server must have TABC certification.', false, 3),
('restaurant', 'TX', 'Food Manager Certification', 'Employee Certification', 'biennial', 80, 200, 250, 2000, 'ANSI-accredited provider', 'https://www.servsafe.com/', 'online', ARRAY['Complete approved course', 'Pass proctored exam'], 'At least 1 manager per establishment must be certified. Valid 5 years. ServSafe, Prometric, or Texas Food Handler approved.', false, 4),
('restaurant', 'TX', 'Workers'' Compensation Insurance', 'Insurance', 'annual', 1500, 10000, 5000, 50000, 'Texas Department of Insurance', 'https://www.tdi.texas.gov/wc/index.html', 'online', ARRAY['Payroll records', 'Business classification', 'Claims history'], 'Technically optional in Texas but highly recommended. Most landlords and contracts require it. Non-subscriber faces full tort liability.', false, 5),
('restaurant', 'TX', 'Sales Tax Permit', 'Tax', 'one_time', 0, 0, 500, 5000, 'Texas Comptroller', 'https://comptroller.texas.gov/taxes/permit/', 'online', ARRAY['Federal EIN', 'SSN', 'Business address'], 'Free. Must file sales tax returns monthly/quarterly. Also covers mixed beverage tax.', false, 6),
('restaurant', 'TX', 'Certificate of Occupancy', 'Building', 'one_time', 200, 2000, 5000, 50000, 'City Building Inspection Department', null, 'in_person', ARRAY['Building inspection', 'Fire inspection clearance', 'Health inspection clearance'], 'Required before opening. Issued after all inspections pass. Post visibly in establishment.', true, 7),
('restaurant', 'TX', 'Dumpster/Grease Trap Permit', 'Environmental', 'annual', 50, 300, 250, 2500, 'City Public Works / Environmental Health', null, 'in_person', ARRAY['Grease trap maintenance records', 'Waste hauler contract'], 'Required by most cities. Grease trap inspection/cleaning typically quarterly. $50-300/yr for permit.', false, 8);

-- Florida
INSERT INTO public.permit_templates (industry, state_code, permit_name, category, typical_renewal_cycle, typical_cost_min, typical_cost_max, penalty_range_min, penalty_range_max, agency_name, agency_url, filing_type, required_docs, tips, is_one_time, sort_order) VALUES
('restaurant', 'FL', 'Food Service License', 'Health & Safety', 'annual', 200, 1000, 1000, 10000, 'Florida Department of Business and Professional Regulation', 'https://www.myfloridalicense.com/DBPR/hotels-restaurants/', 'online', ARRAY['Application', 'Floor plan', 'Equipment list', 'Menu', 'Owner ID'], 'Seating 50-150: ~$400. 150-400: ~$600. 400+: $1,000. Annual inspection required. License is state-level, no local food permit needed.', false, 1),
('restaurant', 'FL', 'Division of Alcoholic Beverages License', 'Alcohol', 'annual', 400, 1500, 2000, 20000, 'Florida DBPR Division of Alcoholic Beverages and Tobacco', 'https://www.myfloridalicense.com/DBPR/alcoholic-beverages-tobacco/', 'online', ARRAY['Application', 'Background check', 'Fingerprints', 'Premises survey'], 'SRX (seating, restaurant, beer/wine): $400-1,000. Full liquor (SFS): $800-1,500. Allow 60-90 days.', false, 2),
('restaurant', 'FL', 'County/City Business Tax Receipt (BTR)', 'Business', 'annual', 25, 300, 200, 2000, 'County Tax Collector', null, 'online', ARRAY['Business info', 'FEIN', 'State license number'], 'Formerly called Occupational License. Required by county AND often city. Miami-Dade: $45-300/yr.', false, 3),
('restaurant', 'FL', 'Sales Tax Registration', 'Tax', 'one_time', 0, 0, 500, 5000, 'Florida Department of Revenue', 'https://floridarevenue.com/taxes/registration/', 'online', ARRAY['Business info', 'FEIN', 'Owner SSN'], 'Free. File monthly or quarterly. Also needed for liquor tax collection.', false, 4),
('restaurant', 'FL', 'Workers'' Compensation', 'Insurance', 'annual', 1500, 12000, 5000, 50000, 'Florida Division of Workers'' Compensation', 'https://www.myfloridacfo.com/division/wc/', 'online', ARRAY['Payroll records', 'Employee count', 'Business classification'], 'Required if 4+ employees (non-construction). Restaurant industry rate ~$4-8/$100 payroll.', false, 5);

-- New York
INSERT INTO public.permit_templates (industry, state_code, permit_name, category, typical_renewal_cycle, typical_cost_min, typical_cost_max, penalty_range_min, penalty_range_max, agency_name, agency_url, filing_type, required_docs, tips, is_one_time, sort_order) VALUES
('restaurant', 'NY', 'Food Service Establishment Permit', 'Health & Safety', 'annual', 100, 500, 1000, 10000, 'NYC Dept of Health (NYC) / County Health Dept (upstate)', 'https://www.nyc.gov/html/doh/html/environmental/permit-food-service.shtml', 'in_person', ARRAY['Application', 'Floor plan', 'Food Protection Certificate', 'Menu'], 'NYC: $280/yr + inspection fee. Upstate varies by county. Inspections A/B/C grade — C grade triggers reinspection.', false, 1),
('restaurant', 'NY', 'Liquor License (On-Premises)', 'Alcohol', 'biennial', 4700, 4700, 5000, 50000, 'NY State Liquor Authority', 'https://sla.ny.gov/', 'in_person', ARRAY['Application', 'Criminal background', 'Financial disclosure', 'Floor plan', 'Community Board notice'], '$4,700 biennial + $200 application. NYC requires 30-day community board notice. Allow 3-6 months. Extremely strict.', false, 2),
('restaurant', 'NY', 'Certificate of Occupancy', 'Building', 'one_time', 500, 5000, 5000, 50000, 'NYC DOB / City Building Department', 'https://www1.nyc.gov/site/buildings/property/certificate-of-occupancy.page', 'in_person', ARRAY['Building inspection', 'Fire code compliance', 'All sub-permits'], 'Required before opening. NYC: Temporary CO often used while permanent is obtained. Very complex in NYC.', true, 3),
('restaurant', 'NY', 'NYC Business Certificate (DBA)', 'Business', 'one_time', 100, 100, 500, 2000, 'NYC County Clerk', 'https://www.nyc.gov/nycbusiness/article/getting-a-business-certificate', 'in_person', ARRAY['Owner ID', 'Business name'], '$100 NYC. Valid indefinitely. Required to open bank account under business name.', true, 4),
('restaurant', 'NY', 'Workers'' Compensation', 'Insurance', 'annual', 2000, 20000, 10000, 100000, 'NY Workers'' Compensation Board', 'https://www.wcb.ny.gov/', 'online', ARRAY['Payroll records', 'Employee info', 'Business classification'], 'Mandatory for all employers. NY rates are among highest in US. Can use NYS Insurance Fund (NYSIF).', false, 5);

-- Washington
INSERT INTO public.permit_templates (industry, state_code, permit_name, category, typical_renewal_cycle, typical_cost_min, typical_cost_max, penalty_range_min, penalty_range_max, agency_name, agency_url, filing_type, required_docs, tips, is_one_time, sort_order) VALUES
('restaurant', 'WA', 'Food Establishment Permit', 'Health & Safety', 'annual', 200, 800, 500, 5000, 'WA State Dept of Health / Local Health Jurisdiction', 'https://www.doh.wa.gov/LicensesPermitsandCertificates/FacilitiesNewReneworUpdate/FoodEstablishments', 'online', ARRAY['Application', 'Floor plan', 'Equipment list', 'Person-in-charge designation'], 'State-issued but administered locally. Seattle fee: ~$350-600/yr. Must designate Person-in-Charge with food safety knowledge.', false, 1),
('restaurant', 'WA', 'Business License (State)', 'Business', 'annual', 19, 19, 250, 2000, 'WA Secretary of State / Dept of Revenue', 'https://dor.wa.gov/open-business/apply-business-license', 'online', ARRAY['Business name', 'Owner info', 'FEIN', 'Business structure'], 'Master Business License: $19/yr. Required for all businesses. Also enables sales tax collection and hiring employees.', false, 2),
('restaurant', 'WA', 'Liquor License (Spirits/Beer/Wine Restaurant)', 'Alcohol', 'annual', 1000, 3000, 2000, 20000, 'Washington State Liquor and Cannabis Board', 'https://lcb.wa.gov/licensing/licensing-overview', 'online', ARRAY['Application', 'Background check', 'Premises plan', 'Public notice'], 'Spirits restaurant license: $2,000-3,000/yr. Beer/wine: $400-800. LCB has online application system.', false, 3),
('restaurant', 'WA', 'City Business License (Seattle)', 'Business', 'annual', 55, 2000, 250, 2000, 'City of Seattle Office of Business Regulations', 'https://seattle.gov/license-and-tax-administration', 'online', ARRAY['State business license', 'Business info', 'Location address'], 'Seattle: $55-2,000+ based on gross revenue. Other WA cities have their own licenses. Check your specific city.', false, 4),
('restaurant', 'WA', 'WSLCB Server Permit', 'Employee Certification', 'annual', 35, 35, 500, 5000, 'WA Liquor and Cannabis Board', 'https://lcb.wa.gov/licensing/mandatory-alcohol-server-training', 'online', ARRAY['Complete MAST (Mandatory Alcohol Server Training)', 'Pass exam', 'Apply online'], 'All alcohol servers/sellers must have MAST permit. $35/yr. 3-hr online course + exam.', false, 5);

-- ============================================================
-- GENERAL CONTRACTOR
-- ============================================================

-- California
INSERT INTO public.permit_templates (industry, state_code, permit_name, category, typical_renewal_cycle, typical_cost_min, typical_cost_max, penalty_range_min, penalty_range_max, agency_name, agency_url, filing_type, required_docs, tips, is_one_time, sort_order) VALUES
('contractor', 'CA', 'CSLB Contractor License', 'Professional License', 'biennial', 300, 500, 5000, 50000, 'California Contractors State License Board', 'https://www.cslb.ca.gov/', 'online', ARRAY['Exam (if first time)', 'Application', 'Workers'' comp certificate', 'Bond ($15,000)', 'Owner fingerprints'], 'Must pass trade exam. Class A (general engineering), B (general building), or specialty (C). Renew every 2 years. $15k bond required.', false, 1),
('contractor', 'CA', 'City Business License', 'Business', 'annual', 50, 500, 250, 2500, 'City Finance / Tax Department', null, 'online', ARRAY['CSLB license number', 'Business formation docs', 'Federal EIN'], 'Required in most CA cities. Often based on gross receipts. Some cities exempt small contractors below certain revenue.', false, 2),
('contractor', 'CA', 'Workers'' Compensation Insurance', 'Insurance', 'annual', 5000, 50000, 10000, 100000, 'California Department of Industrial Relations', 'https://www.dir.ca.gov/dwc/wcinsurance.htm', 'online', ARRAY['Payroll records', 'Employee list', 'CSLB license number'], 'Mandatory and verified by CSLB. Failure to maintain = license suspension. File Certificate of Insurance with CSLB.', false, 3),
('contractor', 'CA', 'General Liability Insurance ($1M minimum)', 'Insurance', 'annual', 2000, 10000, 0, 0, 'Private insurance carrier', null, 'online', ARRAY['Application', 'Business history', 'Prior claims'], 'Not legally required in CA but practically required for all contracts. Most commercial projects require $1M-$2M coverage.', false, 4),
('contractor', 'CA', 'Building Permits (Per Project)', 'Permits', 'per_project', 200, 5000, 5000, 50000, 'City/County Building Department', null, 'in_person', ARRAY['Plans drawn by architect/engineer', 'Site plan', 'Owner authorization'], 'Required for structural work, electrical, plumbing, mechanical. Fees ~1-3% of project cost. Pull permit BEFORE starting work.', false, 5),
('contractor', 'CA', 'EPA Lead-Safe Certification (RRP)', 'Environmental', 'biennial', 300, 300, 37500, 37500, 'EPA / California DPH', 'https://www.epa.gov/lead/lead-renovation-repair-and-painting-program', 'online', ARRAY['Complete 8-hour initial training', 'Pass exam', 'Application to EPA'], 'Required for renovation of pre-1978 homes. EPA fine: $37,500/day. CA has additional requirements. Renew every 5 years.', false, 6),
('contractor', 'CA', 'OSHA 10-Hour Construction', 'Safety', 'one_time', 150, 300, 5000, 25000, 'OSHA-authorized trainer', 'https://www.osha.gov/training/outreach/construction', 'online', ARRAY['Complete 10-hour OSHA outreach course', 'Receive card from trainer'], 'Not legally required in CA but widely expected. OSHA 30-hour recommended for supervisors. Card never expires but knowledge update recommended.', true, 7),
('contractor', 'CA', 'CA DIR Public Works Registration', 'Labor', 'annual', 400, 400, 8000, 100000, 'California Department of Industrial Relations', 'https://www.dir.ca.gov/Public-Works/contractor-registration.html', 'online', ARRAY['Registration form', 'DIR fee', 'Workers'' comp certificate'], 'Required for ALL public works contracts. $400/yr. Must be registered BEFORE bidding public jobs. Non-compliance = contract termination.', false, 8);

-- Texas
INSERT INTO public.permit_templates (industry, state_code, permit_name, category, typical_renewal_cycle, typical_cost_min, typical_cost_max, penalty_range_min, penalty_range_max, agency_name, agency_url, filing_type, required_docs, tips, is_one_time, sort_order) VALUES
('contractor', 'TX', 'Residential Contractor Registration (HB 1325)', 'Professional License', 'annual', 150, 500, 5000, 25000, 'City Building Department (varies)', null, 'online', ARRAY['Proof of insurance', 'Business registration', 'Owner ID'], 'Texas has no state contractor license for general contractors — licensing is CITY-based. Dallas, Austin, Houston all have different requirements. Check your city.', false, 1),
('contractor', 'TX', 'Texas LLC/Business Registration', 'Business', 'annual', 300, 750, 500, 5000, 'Texas Secretary of State', 'https://www.sos.state.tx.us/corp/businessstructure.shtml', 'online', ARRAY['Articles of Organization', 'Registered Agent', 'Federal EIN'], 'File LLC: $300. Must file Annual Franchise Tax Report. Small businesses: $1,180,000 threshold — most pay no franchise tax.', false, 2),
('contractor', 'TX', 'Workers'' Compensation Insurance', 'Insurance', 'annual', 3000, 30000, 0, 0, 'Texas Dept of Insurance', 'https://www.tdi.texas.gov/wc/', 'online', ARRAY['Payroll records', 'Employee info'], 'Technically optional but required for most commercial contracts and government work. Non-subscriber faces full tort liability.', false, 3),
('contractor', 'TX', 'General Liability Insurance', 'Insurance', 'annual', 1500, 8000, 0, 0, 'Private insurance carrier', null, 'online', ARRAY['Application', 'Business history'], 'Required by virtually all clients and contracts. Minimum $1M/$2M coverage. Surety bonds often also required for large projects.', false, 4),
('contractor', 'TX', 'City Business License (Dallas/Austin/Houston)', 'Business', 'annual', 0, 300, 200, 2000, 'City Finance Office', null, 'online', ARRAY['Business registration', 'Location address', 'Trade information'], 'Varies by city. Austin: Contractor Registration $200-450. Dallas: Business License + Contractor Certificate. Houston: generally no general BL required.', false, 5),
('contractor', 'TX', 'OSHA 10/30 Construction', 'Safety', 'one_time', 150, 500, 5000, 25000, 'OSHA-authorized trainer', 'https://www.osha.gov/training/outreach/construction', 'online', ARRAY['Complete OSHA outreach course', 'Receive card'], 'Required on most government and large commercial projects. 10-hour for workers, 30-hour for supervisors.', true, 6),
('contractor', 'TX', 'EPA Lead RRP Certification', 'Environmental', 'biennial', 300, 300, 37500, 37500, 'EPA', 'https://www.epa.gov/lead', 'online', ARRAY['8-hour training', 'Application to EPA'], 'Required for pre-1978 residential work. Texas has additional TDLR lead contractor licensing. $37,500/day EPA fine.', false, 7);

-- Florida
INSERT INTO public.permit_templates (industry, state_code, permit_name, category, typical_renewal_cycle, typical_cost_min, typical_cost_max, penalty_range_min, penalty_range_max, agency_name, agency_url, filing_type, required_docs, tips, is_one_time, sort_order) VALUES
('contractor', 'FL', 'State Certified Contractor License (CBC)', 'Professional License', 'biennial', 300, 500, 5000, 50000, 'Florida DBPR Construction Industry Licensing Board', 'https://www.myfloridalicense.com/DBPR/construction-industry-licensing/', 'online', ARRAY['Exam', 'Application', 'Insurance certificates', 'Financial statements', 'Fingerprints'], 'Certified contractors (CBC) can work statewide. Registered contractors work locally only. CBC requires $300k financial stability.', false, 1),
('contractor', 'FL', 'General Liability Insurance ($300k min)', 'Insurance', 'annual', 2000, 10000, 0, 0, 'Private insurance carrier', null, 'online', ARRAY['Insurance certificate', 'Policy declarations page'], 'State requires $300k GL for CBC. Most commercial contracts require $1M+. File certificate with DBPR.', false, 2),
('contractor', 'FL', 'Workers'' Compensation', 'Insurance', 'annual', 3000, 25000, 5000, 50000, 'Florida Division of Workers'' Compensation', 'https://www.myfloridacfo.com/division/wc/', 'online', ARRAY['Payroll records', 'Employee count', 'Classification codes'], 'Required for all construction employers with 1+ employee. Highest compliance scrutiny in Florida. Unannounced stop-work orders common.', false, 3),
('contractor', 'FL', 'Building Permits (Per Project)', 'Permits', 'per_project', 100, 5000, 2500, 25000, 'County/City Building Department', null, 'in_person', ARRAY['Plans', 'Site plan', 'Owner authorization letter', 'Contractor license copy'], 'Required for nearly all construction. Fees 1-3% of project cost. Pulling without license = 2nd degree misdemeanor.', false, 4);

-- ============================================================
-- HAIR SALON
-- ============================================================

-- California
INSERT INTO public.permit_templates (industry, state_code, permit_name, category, typical_renewal_cycle, typical_cost_min, typical_cost_max, penalty_range_min, penalty_range_max, agency_name, agency_url, filing_type, required_docs, tips, is_one_time, sort_order) VALUES
('salon', 'CA', 'Cosmetology Establishment License', 'Professional License', 'biennial', 50, 200, 500, 5000, 'California Board of Barbering and Cosmetology', 'https://www.barbercosmo.ca.gov/', 'online', ARRAY['Application', 'Floor plan (100 sq ft per operator minimum)', 'Shampoo bowl requirements', 'Sanitation plan'], 'Salon establishment license: $50-200/2yrs. Each operator must have individual cosmetology license. Surprise inspections common.', false, 1),
('salon', 'CA', 'Individual Cosmetology License', 'Professional License', 'biennial', 50, 50, 500, 5000, 'California Board of Barbering and Cosmetology', 'https://www.barbercosmo.ca.gov/', 'online', ARRAY['1600 hours school completion', 'Written and practical exam', 'Application'], 'Each stylist must hold valid individual license. $50/2yrs renewal. 6 CE hours required at renewal.', false, 2),
('salon', 'CA', 'City Business License', 'Business', 'annual', 50, 500, 250, 2500, 'City Finance Department', null, 'online', ARRAY['Board license number', 'Business info', 'EIN'], 'Required in addition to state board license. Fees vary widely by city.', false, 3),
('salon', 'CA', 'Hazardous Materials Business Plan (HMBP)', 'Environmental', 'annual', 100, 500, 500, 5000, 'County Fire / CUPA (Certified Unified Program Agency)', 'https://cers.calepa.ca.gov/', 'online', ARRAY['Inventory of chemicals (hair dye, acetone, etc.)', 'Storage plan', 'Emergency response plan'], 'Required if storing >55 gallons liquid or >500 lbs solid hazardous materials. Most salons qualify. Submit via CERS online portal.', false, 4),
('salon', 'CA', 'Workers'' Comp Insurance', 'Insurance', 'annual', 1000, 5000, 10000, 100000, 'California DIR', null, 'online', ARRAY['Payroll records', 'Employee list'], 'Required for any W-2 employees. Note: 1099 booth renters are not employees — each must have their own coverage.', false, 5);

-- Texas
INSERT INTO public.permit_templates (industry, state_code, permit_name, category, typical_renewal_cycle, typical_cost_min, typical_cost_max, penalty_range_min, penalty_range_max, agency_name, agency_url, filing_type, required_docs, tips, is_one_time, sort_order) VALUES
('salon', 'TX', 'Cosmetology Salon License', 'Professional License', 'annual', 50, 100, 500, 5000, 'Texas Department of Licensing and Regulation (TDLR)', 'https://www.tdlr.texas.gov/cosmet/', 'online', ARRAY['Application', 'Floor plan', 'Equipment list', 'Inspector approval'], 'TDLR salon license: $50-100/yr. Must pass inspection before opening. 50 sq ft minimum per cosmetology station.', false, 1),
('salon', 'TX', 'Individual Cosmetology License', 'Professional License', 'annual', 50, 50, 500, 5000, 'TDLR', 'https://www.tdlr.texas.gov/cosmet/', 'online', ARRAY['1500 hours school', 'Written and practical exam', 'Application'], 'Each operator: $50/yr. Continuing education: 4 hours per renewal cycle.', false, 2),
('salon', 'TX', 'City Business License', 'Business', 'annual', 25, 200, 200, 2000, 'City Finance Office', null, 'online', ARRAY['TDLR license number', 'Business info'], 'Most TX cities require local business license. Check your specific city.', false, 3),
('salon', 'TX', 'Sales Tax Permit (for retail products)', 'Tax', 'one_time', 0, 0, 500, 5000, 'Texas Comptroller', 'https://comptroller.texas.gov/taxes/permit/', 'online', ARRAY['Business info', 'EIN'], 'Required if selling retail products (shampoo, styling products). Free to obtain.', false, 4);

-- ============================================================
-- RETAIL STORE
-- ============================================================

-- California
INSERT INTO public.permit_templates (industry, state_code, permit_name, category, typical_renewal_cycle, typical_cost_min, typical_cost_max, penalty_range_min, penalty_range_max, agency_name, agency_url, filing_type, required_docs, tips, is_one_time, sort_order) VALUES
('retail', 'CA', 'City Business License', 'Business', 'annual', 50, 500, 250, 2500, 'City Finance / Tax Department', null, 'online', ARRAY['Federal EIN', 'Business formation docs', 'Owner ID', 'DBA filing if applicable'], 'Required before opening. Most cities require this even for home-based businesses. Fees often based on gross receipts.', false, 1),
('retail', 'CA', 'Seller''s Permit / Resale Certificate', 'Tax', 'one_time', 0, 0, 1000, 10000, 'California Department of Tax and Fee Administration', 'https://www.cdtfa.ca.gov/', 'online', ARRAY['SSN or ITIN', 'EIN', 'Business address', 'Bank account info'], 'Free. Mandatory for any retail sale. Also allows purchasing inventory tax-exempt. File sales tax monthly/quarterly.', false, 2),
('retail', 'CA', 'Certificate of Occupancy', 'Building', 'one_time', 200, 2000, 5000, 50000, 'City Building Department', null, 'in_person', ARRAY['Building inspection', 'Fire code compliance', 'ADA compliance'], 'Required to occupy commercial space. Landlord typically has CO but you need one for your use type.', true, 3),
('retail', 'CA', 'Signage Permit', 'Building', 'one_time', 50, 500, 100, 1000, 'City Planning Department', null, 'in_person', ARRAY['Sign plans', 'Mounting details', 'Business license'], 'Required for exterior signage. Verify with city before installing any sign.', true, 4),
('retail', 'CA', 'Workers'' Comp Insurance', 'Insurance', 'annual', 1000, 8000, 10000, 100000, 'California DIR', null, 'online', ARRAY['Payroll records', 'Employee list'], 'Required for all employees. Retail rate ~$1.50-3.00/$100 payroll.', false, 5),
('retail', 'CA', 'ADA Compliance', 'Accessibility', 'one_time', 500, 20000, 4000, 150000, 'U.S. DOJ', 'https://www.ada.gov/', 'in_person', ARRAY['Accessibility audit', 'Entrance, aisles, dressing rooms, restrooms accessible'], 'High litigation risk in CA. Serial filers target small retailers. CASp inspection ($300-600) provides some protection.', true, 6);

-- Texas
INSERT INTO public.permit_templates (industry, state_code, permit_name, category, typical_renewal_cycle, typical_cost_min, typical_cost_max, penalty_range_min, penalty_range_max, agency_name, agency_url, filing_type, required_docs, tips, is_one_time, sort_order) VALUES
('retail', 'TX', 'Sales Tax Permit', 'Tax', 'one_time', 0, 0, 500, 5000, 'Texas Comptroller', 'https://comptroller.texas.gov/taxes/permit/', 'online', ARRAY['Business info', 'EIN', 'SSN'], 'Free. Mandatory for all retail sales. File monthly if >$500 tax/month, otherwise quarterly or annually.', false, 1),
('retail', 'TX', 'City Business License', 'Business', 'annual', 0, 200, 200, 2000, 'City Secretary', null, 'online', ARRAY['Business info', 'Location', 'Owner ID'], 'Not all TX cities require this. Houston: generally not required. Dallas, Austin: check city requirements.', false, 2),
('retail', 'TX', 'Certificate of Occupancy', 'Building', 'one_time', 100, 1000, 2500, 25000, 'City Building Inspection', null, 'in_person', ARRAY['Building inspection', 'Fire inspection'], 'Required for new tenant in commercial space or change of use.', true, 3),
('retail', 'TX', 'Special Permits (Alcohol, Tobacco, Firearms)', 'Regulated Products', 'annual', 100, 3000, 5000, 50000, 'TABC / ATF / Texas Comptroller', null, 'online', ARRAY['Application', 'Background check', 'Proof of business', 'Bond (some)'], 'Depends on products sold. Tobacco: TX Comptroller permit. Alcohol: TABC. Firearms: FFL from ATF.', false, 4);

-- ============================================================
-- AUTO REPAIR SHOP
-- ============================================================

-- California
INSERT INTO public.permit_templates (industry, state_code, permit_name, category, typical_renewal_cycle, typical_cost_min, typical_cost_max, penalty_range_min, penalty_range_max, agency_name, agency_url, filing_type, required_docs, tips, is_one_time, sort_order) VALUES
('auto_repair', 'CA', 'Bureau of Automotive Repair License (BAR)', 'Professional License', 'annual', 200, 300, 1000, 15000, 'California Bureau of Automotive Repair', 'https://www.bar.ca.gov/', 'online', ARRAY['Application', 'Business address', 'Owner background check', 'Bond ($10,000)', 'ARD registration'], 'Mandatory for all CA auto repair shops. Also need Automaker Warranty Registration. $200-300/yr. Inspections can be unannounced.', false, 1),
('auto_repair', 'CA', 'Smog Check Program License', 'Professional License', 'biennial', 300, 500, 2000, 20000, 'California Bureau of Automotive Repair', 'https://www.bar.ca.gov/consumer_information/smog_basics.html', 'in_person', ARRAY['BAR license', 'Equipment certification', 'Inspector certification', 'Facility inspection'], 'Required if doing smog inspections. Equipment must be BAR-certified. Inspector must pass BAR exam.', false, 2),
('auto_repair', 'CA', 'City Business License', 'Business', 'annual', 50, 500, 250, 2500, 'City Finance Department', null, 'online', ARRAY['BAR license number', 'Business info', 'EIN'], 'Required in addition to state BAR license.', false, 3),
('auto_repair', 'CA', 'Hazardous Waste Generator Registration', 'Environmental', 'annual', 100, 500, 5000, 50000, 'CalEPA / DTSC', 'https://dtsc.ca.gov/hazardous-waste/', 'online', ARRAY['EPA ID number application', 'Waste manifest records', 'Storage area plan'], 'Auto shops are classified as hazardous waste generators (used oil, solvents, batteries, antifreeze). EPA ID required. Manifests for every shipment.', false, 4),
('auto_repair', 'CA', 'Stormwater Permit / SWPPP', 'Environmental', 'annual', 200, 1000, 10000, 100000, 'Regional Water Quality Control Board', 'https://www.waterboards.ca.gov/', 'online', ARRAY['Site map', 'Stormwater pollution prevention plan', 'Employee training records'], 'Required for outdoor work areas. Prohibits runoff of oil, antifreeze, brake fluid into storm drains. Inspected by local water board.', false, 5),
('auto_repair', 'CA', 'Workers'' Comp Insurance', 'Insurance', 'annual', 3000, 20000, 10000, 100000, 'California DIR', null, 'online', ARRAY['Payroll records', 'Employee list with job classifications'], 'High-risk industry = higher rates (~$8-15/$100 payroll). Required for all employees.', false, 6),
('auto_repair', 'CA', 'Air Quality Permit (Paint Booth)', 'Environmental', 'annual', 500, 2000, 10000, 100000, 'South Coast AQMD / Local Air District', 'https://www.aqmd.gov/', 'in_person', ARRAY['Paint booth specifications', 'Emissions calculations', 'Filters/capture efficiency data'], 'Required if doing body work / painting. Paint booths must meet VOC emission standards. Permit from local air quality district.', false, 7);

-- Texas Auto Repair
INSERT INTO public.permit_templates (industry, state_code, permit_name, category, typical_renewal_cycle, typical_cost_min, typical_cost_max, penalty_range_min, penalty_range_max, agency_name, agency_url, filing_type, required_docs, tips, is_one_time, sort_order) VALUES
('auto_repair', 'TX', 'Motor Vehicle Dealer/Repair License (TxDMV)', 'Professional License', 'annual', 150, 500, 2000, 25000, 'Texas Department of Motor Vehicles', 'https://www.txdmv.gov/', 'online', ARRAY['Application', 'Proof of business location', 'Insurance', 'Bond'], 'Required for dealers. Auto repair shops need Inspection Station License from DPS for state inspection. Separate from dealer license.', false, 1),
('auto_repair', 'TX', 'Vehicle Inspection Station License', 'Professional License', 'annual', 75, 150, 1000, 10000, 'Texas Department of Public Safety', 'https://www.dps.texas.gov/section/vehicle-inspection', 'in_person', ARRAY['Application', 'Equipment certification', 'Inspector certification', 'Facility inspection'], 'Required to perform state vehicle inspections. Inspector must pass DPS certification. Annual station license + per-inspector certification.', false, 2),
('auto_repair', 'TX', 'City Business License', 'Business', 'annual', 25, 200, 200, 2000, 'City Finance Office', null, 'online', ARRAY['Business info', 'Location', 'Owner ID'], 'Varies by city. Some TX cities do not require general business licenses.', false, 3),
('auto_repair', 'TX', 'EPA Hazardous Waste (Small Quantity Generator)', 'Environmental', 'one_time', 0, 200, 10000, 70000, 'EPA / TCEQ', 'https://www.tceq.texas.gov/', 'online', ARRAY['EPA ID number', 'Waste storage plan', 'Manifest records'], 'Must obtain EPA ID number. Used oil, spent solvents, waste antifreeze are hazardous. TCEQ enforces in TX.', false, 4),
('auto_repair', 'TX', 'Workers'' Comp Insurance', 'Insurance', 'annual', 2000, 15000, 0, 0, 'TX Dept of Insurance', null, 'online', ARRAY['Payroll records', 'Employee classifications'], 'Optional in TX but required for most commercial leases and contracts. Auto repair has elevated risk.', false, 5);

-- ============================================================
-- FITNESS STUDIO
-- ============================================================

-- California
INSERT INTO public.permit_templates (industry, state_code, permit_name, category, typical_renewal_cycle, typical_cost_min, typical_cost_max, penalty_range_min, penalty_range_max, agency_name, agency_url, filing_type, required_docs, tips, is_one_time, sort_order) VALUES
('fitness', 'CA', 'City Business License', 'Business', 'annual', 50, 500, 250, 2500, 'City Finance Department', null, 'online', ARRAY['Business info', 'EIN', 'Business structure docs'], 'Required before opening. Fitness studios typically in commercial zoning — verify zoning compliance.', false, 1),
('fitness', 'CA', 'Health Studio Act Compliance', 'Consumer Protection', 'annual', 0, 0, 1000, 25000, 'California AG / DFPI', 'https://dfpi.ca.gov/', 'online', ARRAY['Contract templates reviewed by attorney', 'Refund policy posted', 'Bond ($50k) if prepaid services >1yr'], 'California Health Studio Act governs gym contracts. Illegal to sell >3 months prepaid without performance bond. Heavy AG enforcement.', false, 2),
('fitness', 'CA', 'Certificate of Occupancy (Assembly)', 'Building', 'one_time', 500, 5000, 5000, 50000, 'City Building Department', null, 'in_person', ARRAY['Occupancy load calculation', 'Exit signage', 'Fire suppression if >12k sq ft'], 'Fitness studios = assembly occupancy. Stricter requirements than retail. Higher occupant load ratios.', true, 3),
('fitness', 'CA', 'Personal Trainer Certifications (Staff)', 'Employee Certification', 'biennial', 500, 800, 0, 0, 'NASM / ACE / NSCA / ISSA', 'https://www.nasm.org/', 'online', ARRAY['Complete accredited training program', 'Pass exam', 'CPR/AED certification'], 'Not legally required but standard. Instructors without certification expose studio to liability. NASM/ACE recognized nationally.', false, 4),
('fitness', 'CA', 'CPR/AED Certification (Staff)', 'Employee Certification', 'biennial', 50, 150, 0, 0, 'American Heart Association / Red Cross', 'https://www.heart.org/', 'in_person', ARRAY['Complete hands-on CPR/AED course', 'Pass skills assessment'], 'Required by most fitness studio insurance policies. Renew every 2 years. AED machine also required by CA law for facilities with 200+ members.', false, 5),
('fitness', 'CA', 'Workers'' Comp Insurance', 'Insurance', 'annual', 2000, 10000, 10000, 100000, 'California DIR', null, 'online', ARRAY['Payroll records', 'Employee job classifications'], 'Required for employees. Fitness instructors: often $5-8/$100 payroll. Note: 1099 trainers need their own coverage.', false, 6),
('fitness', 'CA', 'Seller''s Permit (retail supplements/merch)', 'Tax', 'one_time', 0, 0, 500, 5000, 'CDTFA', 'https://www.cdtfa.ca.gov/', 'online', ARRAY['Business info', 'EIN'], 'Required if selling merchandise or supplements. Free to obtain.', false, 7);

-- Texas Fitness
INSERT INTO public.permit_templates (industry, state_code, permit_name, category, typical_renewal_cycle, typical_cost_min, typical_cost_max, penalty_range_min, penalty_range_max, agency_name, agency_url, filing_type, required_docs, tips, is_one_time, sort_order) VALUES
('fitness', 'TX', 'Health Spa Act Bond (if selling prepaid)', 'Consumer Protection', 'annual', 0, 50000, 5000, 50000, 'Texas Secretary of State', 'https://www.sos.state.tx.us/', 'online', ARRAY['Bond from licensed surety', 'Contract templates'], 'Texas Health Spa Act: if selling contracts with prepaid services, must post surety bond. $50k bond if revenue >$100k.', false, 1),
('fitness', 'TX', 'City Business License', 'Business', 'annual', 25, 200, 200, 2000, 'City Finance Office', null, 'online', ARRAY['Business info', 'Location'], 'Varies by city. Dallas, Austin, San Antonio all have own requirements.', false, 2),
('fitness', 'TX', 'Certificate of Occupancy', 'Building', 'one_time', 100, 1500, 2500, 25000, 'City Building Inspection', null, 'in_person', ARRAY['Building inspection', 'Assembly occupancy review', 'Fire inspection'], 'Required for assembly occupancy. Stricter than retail CO.', true, 3),
('fitness', 'TX', 'Sales Tax Permit (merchandise)', 'Tax', 'one_time', 0, 0, 500, 5000, 'Texas Comptroller', null, 'online', ARRAY['Business info', 'EIN'], 'Required for retail sales. Fitness services typically exempt.', false, 4);

-- ============================================================
-- MEDICAL PRACTICE
-- ============================================================

-- California
INSERT INTO public.permit_templates (industry, state_code, permit_name, category, typical_renewal_cycle, typical_cost_min, typical_cost_max, penalty_range_min, penalty_range_max, agency_name, agency_url, filing_type, required_docs, tips, is_one_time, sort_order) VALUES
('medical', 'CA', 'Physician License (MD/DO)', 'Professional License', 'biennial', 800, 1000, 25000, 250000, 'Medical Board of California', 'https://www.mbc.ca.gov/', 'online', ARRAY['CME (50 hrs/2yr)', 'License renewal application', 'Attestation of no violations'], '50 CME hours required every 2 years. License: $800-1,000/2yrs. Failure = practice without license = felony.', false, 1),
('medical', 'CA', 'DEA Controlled Substances Registration', 'Controlled Substances', 'annual', 888, 888, 50000, 500000, 'U.S. Drug Enforcement Administration', 'https://www.deadiversion.usdoj.gov/', 'online', ARRAY['State medical license', 'Application', 'Background check'], 'Required to prescribe Schedule II-V. $888/3yrs (not annual). Separate from state CDS registration.', false, 2),
('medical', 'CA', 'CA Controlled Substance Registration', 'Controlled Substances', 'annual', 100, 200, 10000, 100000, 'California DPH Controlled Substance Utilization Review', 'https://www.cdph.ca.gov/', 'online', ARRAY['CA medical license', 'DEA registration', 'Application'], 'Required in addition to DEA. Separate CA state CDS registration for all prescribers.', false, 3),
('medical', 'CA', 'Business License (Medical Corporation)', 'Business', 'annual', 100, 500, 250, 2500, 'City Finance Department', null, 'online', ARRAY['Medical corporation formation docs', 'EIN', 'Secretary of State filing'], 'CA requires medical practices to be Medical Professional Corporations (MMC). General corporation not allowed.', false, 4),
('medical', 'CA', 'X-Ray Machine Registration', 'Equipment', 'annual', 100, 300, 1000, 25000, 'California Dept of Public Health - Radiologic Health', 'https://www.cdph.ca.gov/Programs/CEH/DRSEM/Pages/RHB.aspx', 'online', ARRAY['Machine specs', 'Lead shielding certification', 'Operator training records'], 'Required for any X-ray equipment. Also need radiation technologist licenses for operators.', false, 5),
('medical', 'CA', 'CLIA Certificate (Lab Work)', 'Equipment', 'biennial', 150, 2000, 10000, 100000, 'CMS / California DPH', 'https://www.cms.gov/Regulations-and-Guidance/Legislation/CLIA', 'online', ARRAY['Application', 'Test menu', 'Lab director qualifications'], 'Required for any in-house lab testing. Certificate of Waiver ($150/2yrs) for basic tests. Complex tests require higher certificate level.', false, 6),
('medical', 'CA', 'HIPAA Compliance Program', 'Privacy', 'annual', 1000, 10000, 100, 50000, 'HHS Office for Civil Rights', 'https://www.hhs.gov/hipaa/', 'online', ARRAY['Privacy policies', 'BAA with vendors', 'Staff training records', 'Risk assessment'], 'Not a permit but a federal requirement. Annual risk assessments, staff training, BAAs with all vendors. Fines $100-$50k per violation.', false, 7),
('medical', 'CA', 'Workers'' Comp Insurance', 'Insurance', 'annual', 3000, 20000, 10000, 100000, 'California DIR', null, 'online', ARRAY['Payroll records', 'Employee classifications'], 'Higher rates for medical staff. Nurses: ~$4-6/$100 payroll. Physicians: ~$2-3/$100.', false, 8);

-- ============================================================
-- REAL ESTATE AGENCY
-- ============================================================

-- California
INSERT INTO public.permit_templates (industry, state_code, permit_name, category, typical_renewal_cycle, typical_cost_min, typical_cost_max, penalty_range_min, penalty_range_max, agency_name, agency_url, filing_type, required_docs, tips, is_one_time, sort_order) VALUES
('realestate', 'CA', 'Real Estate Broker License', 'Professional License', 'biennial', 300, 450, 25000, 250000, 'California Department of Real Estate', 'https://www.dre.ca.gov/', 'online', ARRAY['45 CE hours per 2yr', 'License renewal application', 'All agent BRE license numbers'], 'Broker license: $300-450/2yrs. Each agent must hold salesperson license sponsored by broker. 45 CE hours required.', false, 1),
('realestate', 'CA', 'Salesperson License (per agent)', 'Professional License', 'biennial', 245, 245, 5000, 50000, 'California Department of Real Estate', 'https://www.dre.ca.gov/', 'online', ARRAY['45 CE hours per 2yr', 'Active broker sponsorship', 'Renewal application'], '$245/2yrs per agent. Agents are personally responsible for their own license. Agency responsible for monitoring.', false, 2),
('realestate', 'CA', 'City Business License', 'Business', 'annual', 50, 500, 250, 2500, 'City Finance Department', null, 'online', ARRAY['DRE license numbers', 'Business info', 'EIN'], 'Required for physical office location.', false, 3),
('realestate', 'CA', 'Errors & Omissions Insurance', 'Insurance', 'annual', 2000, 10000, 0, 0, 'Private insurance carrier', null, 'online', ARRAY['Application', 'Claims history', 'License numbers'], 'Not legally required but practically mandatory. Most brokerages require E&O. Covers professional negligence claims.', false, 4);

-- ============================================================
-- Remaining states for Restaurant (IL, GA, AZ, CO, OH, PA, NC)
-- ============================================================

-- Illinois Restaurant
INSERT INTO public.permit_templates (industry, state_code, permit_name, category, typical_renewal_cycle, typical_cost_min, typical_cost_max, penalty_range_min, penalty_range_max, agency_name, agency_url, filing_type, required_docs, tips, is_one_time, sort_order) VALUES
('restaurant', 'IL', 'Food Service Sanitation License', 'Health & Safety', 'annual', 100, 600, 500, 10000, 'Illinois Dept of Public Health (Chicago: CDPH)', 'https://www.dph.illinois.gov/', 'online', ARRAY['Application', 'Floor plan', 'Food Safety Manager cert', 'Menu', 'Owner info'], 'Chicago: Chicago Department of Public Health issues separately. State license for non-Chicago. Fee varies by seating: ~$100-600/yr.', false, 1),
('restaurant', 'IL', 'City Business License (Chicago)', 'Business', 'annual', 200, 500, 500, 5000, 'City of Chicago BACP', 'https://www.chicago.gov/city/en/depts/bacp.html', 'online', ARRAY['All sub-licenses', 'Certificate of Occupancy', 'Zoning confirmation', 'Food service inspection'], 'Chicago requires Retail Food License ($660-$1,320 for restaurant). Complex multi-step process with BACP. Allow 6-12 weeks.', false, 2),
('restaurant', 'IL', 'Liquor License (City of Chicago)', 'Alcohol', 'annual', 3000, 10000, 10000, 100000, 'City of Chicago Dept of Business Affairs', 'https://www.chicago.gov/city/en/depts/bacp/supp_info/liquor_licensing_information.html', 'online', ARRAY['Application', 'Background check', 'Aldermanic approval', 'State liquor license', 'Surety bond'], 'Chicago liquor licenses are extremely complex and expensive. Most Chicago aldermen must approve. Budget 6-12 months and legal help.', false, 3);

-- Georgia Restaurant
INSERT INTO public.permit_templates (industry, state_code, permit_name, category, typical_renewal_cycle, typical_cost_min, typical_cost_max, penalty_range_min, penalty_range_max, agency_name, agency_url, filing_type, required_docs, tips, is_one_time, sort_order) VALUES
('restaurant', 'GA', 'Food Service Permit', 'Health & Safety', 'annual', 100, 500, 500, 5000, 'Georgia Dept of Public Health / County Health Dept', 'https://dph.georgia.gov/environmental-health/food-service', 'in_person', ARRAY['Application', 'Floor plan', 'Equipment list', 'Food Safety Manager cert', 'Menu'], 'Issued at county level. Fulton County (Atlanta): ~$350-500/yr. Inspection required before opening and annually.', false, 1),
('restaurant', 'GA', 'Business License (City/County)', 'Business', 'annual', 75, 400, 250, 2500, 'City/County Business License Office', null, 'online', ARRAY['Business info', 'FEIN', 'Business structure docs'], 'City and county both may require. Atlanta: $75-400/yr based on gross receipts.', false, 2),
('restaurant', 'GA', 'Retail Liquor/Beer/Wine License', 'Alcohol', 'annual', 500, 5000, 2000, 25000, 'Georgia Dept of Revenue / City', 'https://dor.georgia.gov/alcohol-licensing', 'online', ARRAY['State application', 'City approval', 'Background check', 'Criminal background', 'Surety bond'], 'Both state AND city licenses required. Many GA counties are "dry" — check local laws. Atlanta: wine/beer ~$500, liquor ~$3,000+/yr.', false, 3);

-- Arizona Restaurant
INSERT INTO public.permit_templates (industry, state_code, permit_name, category, typical_renewal_cycle, typical_cost_min, typical_cost_max, penalty_range_min, penalty_range_max, agency_name, agency_url, filing_type, required_docs, tips, is_one_time, sort_order) VALUES
('restaurant', 'AZ', 'Food Establishment License', 'Health & Safety', 'annual', 100, 500, 500, 10000, 'Maricopa County Environmental Services / AZ ADHS', 'https://www.azdhs.gov/', 'online', ARRAY['Application', 'Floor plan', 'Food Safety Manager cert', 'Menu', 'Equipment list'], 'County-issued in Maricopa/Pima. State for others. Maricopa: ~$100-400/yr. Annual inspection required.', false, 1),
('restaurant', 'AZ', 'City Business License', 'Business', 'annual', 50, 200, 200, 2000, 'City Clerk Office', null, 'online', ARRAY['Business info', 'FEIN', 'Business structure'], 'Phoenix: no general business license! Scottsdale, Tempe, Mesa: all different requirements. Check your specific city.', false, 2),
('restaurant', 'AZ', 'AZ Liquor License', 'Alcohol', 'annual', 500, 3000, 5000, 50000, 'Arizona Dept of Liquor Licenses and Control', 'https://www.azliquor.gov/', 'online', ARRAY['Application', 'Background check', 'Fingerprints', 'Site plan', 'Premises description'], 'Series 12 (restaurant): $500-1,500/yr. Series 6 (bar): $2,000-3,000. Applications public — neighbors can protest. Allow 90 days.', false, 3);

-- Colorado Restaurant
INSERT INTO public.permit_templates (industry, state_code, permit_name, category, typical_renewal_cycle, typical_cost_min, typical_cost_max, penalty_range_min, penalty_range_max, agency_name, agency_url, filing_type, required_docs, tips, is_one_time, sort_order) VALUES
('restaurant', 'CO', 'Retail Food Establishment License', 'Health & Safety', 'annual', 100, 500, 500, 10000, 'Colorado Dept of Public Health / County Health', 'https://cdphe.colorado.gov/', 'in_person', ARRAY['Application', 'Floor plan', 'Food Safety Manager cert', 'Equipment list'], 'Denver: Dept of Public Health issues locally. Other counties: county health dept. ~$150-500/yr.', false, 1),
('restaurant', 'CO', 'Sales Tax License', 'Tax', 'annual', 0, 50, 500, 5000, 'Colorado Dept of Revenue', 'https://tax.colorado.gov/', 'online', ARRAY['Business info', 'FEIN', 'Business address'], '$16 initial + free renewal. Required to collect CO state sales tax.', false, 2),
('restaurant', 'CO', 'Liquor License', 'Alcohol', 'annual', 500, 2500, 5000, 50000, 'Colorado Liquor Enforcement Division', 'https://sbg.colorado.gov/liquor', 'online', ARRAY['Application', 'Background check', 'Financial disclosure', 'Premises plan', 'Local approval'], 'Hotel/Restaurant license: $500-2,500/yr. Must get local government approval first. 30-day public notice. Allow 60-90 days.', false, 3);

-- Ohio Restaurant
INSERT INTO public.permit_templates (industry, state_code, permit_name, category, typical_renewal_cycle, typical_cost_min, typical_cost_max, penalty_range_min, penalty_range_max, agency_name, agency_url, filing_type, required_docs, tips, is_one_time, sort_order) VALUES
('restaurant', 'OH', 'Food Service Operation License (FSO)', 'Health & Safety', 'annual', 25, 700, 500, 10000, 'Ohio Dept of Agriculture / Local Health District', 'https://agri.ohio.gov/divisions/food-safety', 'online', ARRAY['Application', 'Floor plan', 'Food Safety Manager cert', 'Menu'], 'Risk Level 1-4. Level 4 (high risk): $500-700. Level 1 (low): $25-150. Inspections 1-4x/yr based on risk level.', false, 1),
('restaurant', 'OH', 'Liquor License (D1-D5)', 'Alcohol', 'annual', 150, 1800, 5000, 50000, 'Ohio Department of Commerce - Division of Liquor Control', 'https://www.com.ohio.gov/DISLIQ', 'online', ARRAY['Application', 'Background check', 'Premises description', 'Local approval'], 'D5 (beer/wine/liquor until 2am): $1,800/yr. D1 (beer only): $150/yr. Local government must approve. Allow 60 days.', false, 2),
('restaurant', 'OH', 'Vendor''s License (Sales Tax)', 'Tax', 'one_time', 25, 25, 500, 5000, 'Ohio Dept of Taxation', 'https://tax.ohio.gov/', 'online', ARRAY['Business info', 'FEIN', 'Business address'], '$25 one-time. Required to collect Ohio sales tax. File returns monthly/quarterly.', false, 3);

-- Pennsylvania Restaurant
INSERT INTO public.permit_templates (industry, state_code, permit_name, category, typical_renewal_cycle, typical_cost_min, typical_cost_max, penalty_range_min, penalty_range_max, agency_name, agency_url, filing_type, required_docs, tips, is_one_time, sort_order) VALUES
('restaurant', 'PA', 'Food Facility License', 'Health & Safety', 'annual', 100, 600, 500, 10000, 'PA Dept of Agriculture / County Health Dept (Philadelphia/Allegheny)', 'https://www.agriculture.pa.gov/', 'online', ARRAY['Application', 'Floor plan', 'Food Safety Manager cert', 'Menu'], 'Philadelphia/Allegheny counties self-regulate. State issues for other counties. ~$150-600/yr based on seating/sales.', false, 1),
('restaurant', 'PA', 'Pennsylvania Liquor License', 'Alcohol', 'annual', 1500, 3500, 5000, 50000, 'Pennsylvania Liquor Control Board (PLCB)', 'https://www.lcb.pa.gov/', 'in_person', ARRAY['Application', 'Background check', 'Premises description', 'Local approval', 'Renovation plans (if applicable)'], 'R (restaurant) license: $1,250-3,500/yr. Very complex — quota system means new licenses must be bought on open market ($50k-200k+). Consult attorney.', false, 2),
('restaurant', 'PA', 'City/Business Privilege License (Philadelphia)', 'Business', 'annual', 300, 800, 500, 5000, 'City of Philadelphia L&I', 'https://www.phila.gov/departments/department-of-licenses-and-inspections/', 'online', ARRAY['Business info', 'Zoning confirmation', 'All relevant sub-licenses'], 'Philadelphia requires Commercial Activity License. Pittsburgh requires Business License. Rural areas: usually just county-level.', false, 3);

-- North Carolina Restaurant
INSERT INTO public.permit_templates (industry, state_code, permit_name, category, typical_renewal_cycle, typical_cost_min, typical_cost_max, penalty_range_min, penalty_range_max, agency_name, agency_url, filing_type, required_docs, tips, is_one_time, sort_order) VALUES
('restaurant', 'NC', 'Food Service Permit', 'Health & Safety', 'annual', 100, 500, 500, 10000, 'NC Dept of Health and Human Services / Local Health Dept', 'https://www.ncdhhs.gov/divisions/environmental-health', 'in_person', ARRAY['Application', 'Floor plan', 'Food Safety Manager cert', 'Equipment list'], 'County-issued. Wake County (Raleigh): ~$200-400/yr. Mecklenburg (Charlotte): ~$300-500/yr. Annual graded inspection (A/B/C).', false, 1),
('restaurant', 'NC', 'Privilege License (City)', 'Business', 'annual', 25, 200, 200, 2000, 'City/Town Finance Office', null, 'online', ARRAY['Business info', 'Health permit copy', 'FEIN'], 'Most NC cities require a privilege license. Charlotte: ~$25-200/yr. Raleigh: business license required. Varies by revenue.', false, 2),
('restaurant', 'NC', 'ABC Permit', 'Alcohol', 'annual', 500, 2000, 2000, 20000, 'NC Alcoholic Beverage Control Commission', 'https://abc.nc.gov/', 'in_person', ARRAY['Application', 'Background check', 'Location approval', 'Local ABC board approval'], 'On-premises malt beverage/wine: $500-800. Mixed beverages: $1,000-2,000. Local ABC board must approve. Allow 60-90 days.', false, 3);

-- Contractor remaining states
INSERT INTO public.permit_templates (industry, state_code, permit_name, category, typical_renewal_cycle, typical_cost_min, typical_cost_max, penalty_range_min, penalty_range_max, agency_name, agency_url, filing_type, required_docs, tips, is_one_time, sort_order) VALUES
('contractor', 'WA', 'Contractor Registration', 'Professional License', 'annual', 113, 113, 5000, 50000, 'Washington Labor & Industries', 'https://www.lni.wa.gov/licensing-permits/contractors/register-as-a-contractor', 'online', ARRAY['Application', 'Surety bond ($12k general)', 'Liability insurance', 'UBI number'], 'All contractors must register with L&I. $113/yr + $12k bond. Unlicensed contractor: $6,000-10,000 fine per violation.', false, 1),
('contractor', 'WA', 'City Business License', 'Business', 'annual', 19, 200, 250, 2500, 'WA Dept of Revenue + City', 'https://dor.wa.gov/', 'online', ARRAY['State master business license', 'Location address'], 'State master license: $19/yr. Plus city endorsement if operating in incorporated city.', false, 2),
('contractor', 'WA', 'Workers'' Comp (L&I Coverage)', 'Insurance', 'annual', 2000, 20000, 10000, 100000, 'Washington Labor & Industries', 'https://www.lni.wa.gov/insurance/', 'online', ARRAY['Payroll records', 'Employee hours', 'Risk classification'], 'WA uses state fund system. All employers with workers must pay L&I premiums. No private workers'' comp in WA for basic coverage.', false, 3),

('contractor', 'IL', 'Roofing Contractor License (IL)', 'Professional License', 'annual', 100, 500, 5000, 50000, 'Illinois Dept of Financial and Professional Regulation', 'https://idfpr.illinois.gov/', 'online', ARRAY['Application', 'Exam (roofing)', 'Insurance', 'Bond'], 'IL licenses specialty contractors (roofing, plumbing, electrical) separately. Chicago has its own contractor licensing. General contractors: largely city-regulated.', false, 1),
('contractor', 'IL', 'Chicago Contractor License', 'Professional License', 'annual', 150, 500, 5000, 50000, 'City of Chicago BACP', 'https://www.chicago.gov/city/en/depts/bacp.html', 'online', ARRAY['Application', 'Insurance certificates', 'Background check', 'Bond'], 'Chicago has comprehensive contractor licensing separate from IL state. Required for any construction work within city limits.', false, 2),

('contractor', 'NY', 'Home Improvement Contractor Registration (NYC HIC)', 'Professional License', 'biennial', 200, 200, 500, 25000, 'NYC Department of Consumer Affairs (DCA)', 'https://www1.nyc.gov/nycbusiness/article/home-improvement-contractor-licensing', 'online', ARRAY['Application', 'Insurance ($1M GL, $500k WC)', 'Home address', 'Fingerprints'], 'Required for all home improvement work in NYC. $200/2yrs. Must post registration number in all contracts and ads.', false, 1),
('contractor', 'NY', 'Suffolk/Nassau/Westchester County License', 'Professional License', 'annual', 100, 400, 500, 25000, 'County Consumer Affairs', null, 'online', ARRAY['Application', 'Insurance', 'Background check'], 'Each county has own licensing. NYC boroughs: NYC HIC. Long Island counties: separate county licenses.', false, 2);
